version: '3'

volumes:
    postgres:

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.web
        container_name: kenshu-backend_laravel_web
        volumes:
            - .:/var/www/kenshu_backend_laravel
            - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
        ports:
            - ${WEB_PORT}:80
        depends_on:
            - db

    db:
        image: postgres:12
        container_name: kenshu_backend_laravel_db
        volumes:
            - postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
        ports:
            - ${DB_PORT}:5432
