version: '3'

volumes:
    mysql:

services:
    web:
        image: nginx:stable
        container_name: kenshu-backend-laravel_web
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/kenshu-backend-laravel/
        ports:
            - ${WEB_PORT}:80
        depends_on:
            - app

    app:
        build:
            context: .
            dockerfile: Dockerfile.app
        container_name: kenshu-backend-laravel_app
        volumes:
            - ./:/kenshu-backend-laravel/
        depends_on:
            - db
        ports:
            - 9000:9000

    db:
        image: mysql:5.7
        container_name: kenshu-backend-laravel_db
        volumes:
            - mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_USER=${DB_USERNAME}
