FROM php:8.1.5-apache

WORKDIR /var/www/kenshu_backend_laravel

COPY . .

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN apt-get update && apt-get install -y git

RUN docker-php-ext-install pdo_pgsql pgsql
